os: Visual Studio 2015

before_build:
  - nuget restore

build:
  project: src\SshNet.Security.Cryptography.VS2015.sln
  verbosity: minimal

test:
  assemblies: test\SshNet.Security.Cryptography.NET40.Tests\bin\Debug\SshNet.Security.Cryptography.Tests.dll
